spring:
  datasource:
    url: jdbc:postgresql://dpg-d6gnh6fkijhs73f17h3g-a.oregon-postgres.render.com:5432/springboot_db_jckr
    username: springboot_db_jckr_user
    password: qk470rwkI2IaKv1hU9Ob54xupD2gJ2N6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false

# server:
#   port: ${PORT:8080}
